services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  viewer:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: database
    ports:
      - "8080:80"